# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/ruby/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),ruby)

$(call add-radio-file-sha1-checked,radio/audio_dsp.img,56104cf4d5fb001488fcc57a56e66caf0c766ac4)
$(call add-radio-file-sha1-checked,radio/cam_vpu1.img,0d13ce36fc36f1cbe87c4cfe59beb8a82bd67b06)
$(call add-radio-file-sha1-checked,radio/cam_vpu2.img,1d17b4c03b51ab8fcf8a22f2ea33699b142f5ad1)
$(call add-radio-file-sha1-checked,radio/cam_vpu3.img,67ce3885fcd72ca6dd1a9ee4d1748abd077f953f)
$(call add-radio-file-sha1-checked,radio/dpm.img,0245c029202b49b5f775d7556f3313165e08a4ba)
$(call add-radio-file-sha1-checked,radio/gz.img,2d1bdc1ac54eea4796c3a24eaddc1097152db581)
$(call add-radio-file-sha1-checked,radio/lk.img,350b7df76a9b731c4634f8cbed0d6ad7d8ab55ee)
$(call add-radio-file-sha1-checked,radio/logo.img,8fcc15090139a98e8f73c11296dab7eefe3b2b29)
$(call add-radio-file-sha1-checked,radio/mcupm.img,e63fb4a57b0e6018e0f44755477bb432c39c95de)
$(call add-radio-file-sha1-checked,radio/md1img.img,a9997ec1706dc24629fc4b36adbdf64d739f5fea)
$(call add-radio-file-sha1-checked,radio/pi_img.img,4a45fe632ff7b392421eba51d94043a98c38d3f5)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,ef0e74d258dfe2379ea296bc7864780ba2ea81f9)
$(call add-radio-file-sha1-checked,radio/scp.img,39f5bb4451d96c132ef7e5ae565e44643e6cdae8)
$(call add-radio-file-sha1-checked,radio/spmfw.img,dfae7d70ff0b7984a85dbdfd62520734e012b9e3)
$(call add-radio-file-sha1-checked,radio/sspm.img,dfb49afec1b787d9a521ae5b063adca0019ac084)
$(call add-radio-file-sha1-checked,radio/tee.img,3ee3afb8f1419ff091eb3900e26f1c5d792c32d5)

endif
