# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/ruby/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),ruby)

$(call add-radio-file-sha1-checked,radio/audio_dsp.img,7c0a36121cc02a36328e1d1fa95cfa07f11765cd)
$(call add-radio-file-sha1-checked,radio/cam_vpu1.img,5f1ffa04a540e8a86f059e8410ca48b32a9e41ad)
$(call add-radio-file-sha1-checked,radio/cam_vpu2.img,a4f975b3750a18b0a158b6b9646d68b3dc5d1796)
$(call add-radio-file-sha1-checked,radio/cam_vpu3.img,ec8771ab31700e132b75d9afe8a32e3a75c07824)
$(call add-radio-file-sha1-checked,radio/dpm.img,99e74f5915c9c24728ccef105ea1adce870909dd)
$(call add-radio-file-sha1-checked,radio/gz.img,6779535b41449e6662e520029c2e28785fb5a03e)
$(call add-radio-file-sha1-checked,radio/lk.img,f171dcac5d2f9751282c4c75eed63f42b279c000)
$(call add-radio-file-sha1-checked,radio/logo.img,40d1fcec92d4d8e30c40b0c0bb56f1468a111569)
$(call add-radio-file-sha1-checked,radio/mcupm.img,4dc1552cd64399dc8934230fe8f15838e18f1dac)
$(call add-radio-file-sha1-checked,radio/md1img.img,180c3ca93dd6f6f94988f37fcb02e32f069087e4)
$(call add-radio-file-sha1-checked,radio/pi_img.img,675f6e2fd12278ca290da252371a9785fdfc5e07)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,4101a47bc69deb58161e37caaed18f9075d047c9)
$(call add-radio-file-sha1-checked,radio/scp.img,885fda47eb7cd743cc57398692596124a17d30d1)
$(call add-radio-file-sha1-checked,radio/spmfw.img,20c828810138e26a583298c4c511a83dc327a17d)
$(call add-radio-file-sha1-checked,radio/sspm.img,d56bbb30c237a79195a2216243c7a62c4a5f5866)
$(call add-radio-file-sha1-checked,radio/tee.img,d410026e32478c428020c78b8f31d16156ae890f)

endif
