# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/ruby/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),ruby)

$(call add-radio-file-sha1-checked,radio/audio_dsp.img,a0239b6e113c8c6847ec26d9a4dea291f8780465)
$(call add-radio-file-sha1-checked,radio/cam_vpu1.img,e182721a53f5f658e104c995da3f8e3bbc18917b)
$(call add-radio-file-sha1-checked,radio/cam_vpu2.img,ee432b5eef85ac12cc4a6e6b1a1d724590b4a923)
$(call add-radio-file-sha1-checked,radio/cam_vpu3.img,8a1da3b667eecd6aa92064b14d3c197fd6db4b58)
$(call add-radio-file-sha1-checked,radio/dpm.img,2a1b09d9e935316ceab6229c55e7f23adcc33f9e)
$(call add-radio-file-sha1-checked,radio/gz.img,c921bfdb6b38f6e0c3bf0101852eb305103b61c0)
$(call add-radio-file-sha1-checked,radio/lk.img,c87bdb35402482450c78cf5aaaf819260db2deb9)
$(call add-radio-file-sha1-checked,radio/logo.img,a4c97198c358589d197ee04d4742b9d995199484)
$(call add-radio-file-sha1-checked,radio/mcupm.img,2448de8ebd7adb98feecb2f151582f241f2ea275)
$(call add-radio-file-sha1-checked,radio/md1img.img,3a0a61db49c8ee241c93b2bf49ddf6303ea8b604)
$(call add-radio-file-sha1-checked,radio/pi_img.img,9447a5f5c9c6f427f718e9929e66861c8980a080)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,5825a5e8af1e7159c36231616f00d78af5a89c22)
$(call add-radio-file-sha1-checked,radio/scp.img,97e345f7ab14c670b410d122f29bd8710aae1f39)
$(call add-radio-file-sha1-checked,radio/spmfw.img,c38d58fed8f890b53b02f8c8a3eafb5190347319)
$(call add-radio-file-sha1-checked,radio/sspm.img,e6c3a35384fde76cf9a0d7c8ad0b92663e7638cb)
$(call add-radio-file-sha1-checked,radio/tee.img,f7402b09aaace3a1776dc84a1088554e7de3f02a)

endif
